/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.renatathiago.trabalhoBim2.Ui.JFrames;

import br.cefet.renatathiago.trabalhoBim2.Controle.FornecedorControle;
import br.cefet.renatathiago.trabalhoBim2.Entidade.Fornecedor;
import br.cefet.renatathiago.trabalhoBim2.Excecoes.DaoException;
import br.cefet.renatathiago.trabalhoBim2.Utilidades.CellRenderer;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class CUDFornecedor extends javax.swing.JFrame {

    private FornecedorControle fControle = new FornecedorControle();
    private Fornecedor forn = new Fornecedor();
    private BuscaFornecedor bFornecedor = new BuscaFornecedor();

    public CUDFornecedor() {
        initComponents();
        CodFornecedorJTF.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FoneFornecedorLabel = new javax.swing.JLabel();
        FoneFornecedorJTF = new javax.swing.JTextField();
        CnpjFornecedorLabel = new javax.swing.JLabel();
        CnpjFornecedorJTF = new javax.swing.JTextField();
        CodFornecedorLabel = new javax.swing.JLabel();
        CodFornecedorJTF = new javax.swing.JTextField();
        BotaoCadastroFornecedor = new javax.swing.JButton();
        BotaoEditarFornecedor = new javax.swing.JButton();
        BotaoExcluirFornecedor = new javax.swing.JButton();
        NomeFornecedorLabel = new javax.swing.JLabel();
        NomeFornecedorJTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FoneFornecedorLabel.setText("Telefone");
        getContentPane().add(FoneFornecedorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, -1, -1));
        getContentPane().add(FoneFornecedorJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 135, -1));

        CnpjFornecedorLabel.setText("CNPJ");
        getContentPane().add(CnpjFornecedorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 140, -1, -1));
        getContentPane().add(CnpjFornecedorJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 164, 147, -1));

        CodFornecedorLabel.setText("Código");
        getContentPane().add(CodFornecedorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        CodFornecedorJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodFornecedorJTFActionPerformed(evt);
            }
        });
        getContentPane().add(CodFornecedorJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 300, -1));

        BotaoCadastroFornecedor.setText("Cadastrar");
        BotaoCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 471, 92, -1));

        BotaoEditarFornecedor.setText("Salvar");
        BotaoEditarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEditarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 471, 92, -1));

        BotaoExcluirFornecedor.setText("Excluir");
        BotaoExcluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoExcluirFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 471, 92, -1));

        NomeFornecedorLabel.setText("Nome Completo");
        getContentPane().add(NomeFornecedorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        NomeFornecedorJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFornecedorJTFActionPerformed(evt);
            }
        });
        getContentPane().add(NomeFornecedorJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 98, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodFornecedorJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodFornecedorJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodFornecedorJTFActionPerformed

    private void BotaoCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroFornecedorActionPerformed

        forn.setCnpj(CnpjFornecedorJTF.getText());
        forn.setNome(NomeFornecedorJTF.getText());
        forn.setTelefone(FoneFornecedorJTF.getText());
        try {
            if (validarFornecedor(forn)){
                fControle.inserirFornecedor(forn);
                bFornecedor.consultarTodos();
                limparDados();
                definirCod();
                habilitarBotaoCadastrar();
                
            }
        } catch (DaoException ex) {
            Logger.getLogger(CUDFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoCadastroFornecedorActionPerformed

    private void BotaoEditarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarFornecedorActionPerformed
        forn.setCod(Integer.parseInt(CodFornecedorJTF.getText()));
        forn.setCnpj(CnpjFornecedorJTF.getText());
        forn.setNome(NomeFornecedorJTF.getText());
        forn.setTelefone(FoneFornecedorJTF.getText());
        try {
            if (validarFornecedor(forn)){
                fControle.alterarFornecedor(Integer.parseInt(CodFornecedorJTF.getText()), forn);
                bFornecedor.consultarTodos();
                limparDados();
                definirCod();
                BotaoEditarFornecedor.setEnabled(false);
                BotaoCadastroFornecedor.setEnabled(true);
            }
        } catch (DaoException ex) {
            Logger.getLogger(CUDFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoEditarFornecedorActionPerformed

    private void BotaoExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirFornecedorActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Excluir Fornecedor", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                fControle.excluirFornecedor(Integer.parseInt(CodFornecedorJTF.getText()));
                limparDados();
                bFornecedor.consultarTodos();
                definirCod();
                habilitarBotaoCadastrar();
            } catch (DaoException ex) {
                Logger.getLogger(CUDFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BotaoExcluirFornecedorActionPerformed

    private void NomeFornecedorJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFornecedorJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFornecedorJTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastroFornecedor;
    private javax.swing.JButton BotaoEditarFornecedor;
    private javax.swing.JButton BotaoExcluirFornecedor;
    private javax.swing.JTextField CnpjFornecedorJTF;
    private javax.swing.JLabel CnpjFornecedorLabel;
    private javax.swing.JTextField CodFornecedorJTF;
    private javax.swing.JLabel CodFornecedorLabel;
    private javax.swing.JTextField FoneFornecedorJTF;
    private javax.swing.JLabel FoneFornecedorLabel;
    private javax.swing.JTextField NomeFornecedorJTF;
    private javax.swing.JLabel NomeFornecedorLabel;
    // End of variables declaration//GEN-END:variables

void desabilitarBotaoCadastrar() {
        BotaoCadastroFornecedor.setEnabled(false);
    }

    void desabilitarBotaoEditar() {
        BotaoEditarFornecedor.setEnabled(false);
    }

    void desabilitarBotaoExcluir() {
        BotaoExcluirFornecedor.setEnabled(false);
    }
    
    void habilitarBotaoCadastrar() {
        BotaoCadastroFornecedor.setEnabled(true);
    }

    void habilitarBotaoEditar() {
        BotaoEditarFornecedor.setEnabled(true);
    }

    void habilitarBotaoExcluir() {
        BotaoExcluirFornecedor.setEnabled(true);
    }

    void desabilitarJTF(){
        NomeFornecedorJTF.setEnabled(false);
        FoneFornecedorJTF.setEnabled(false);
        CnpjFornecedorJTF.setEnabled(false);
    }
    void habilitarJTF(){
        NomeFornecedorJTF.setEnabled(true);
        FoneFornecedorJTF.setEnabled(true);
        CnpjFornecedorJTF.setEnabled(true);
    }

    

     void exibirDados(Fornecedor a) {
        NomeFornecedorJTF.setText(a.getNome());
        CodFornecedorJTF.setText(Integer.toString(a.getCod()));
        FoneFornecedorJTF.setText(a.getTelefone());
        CnpjFornecedorJTF.setText(a.getCnpj());
        BotaoExcluirFornecedor.setEnabled(true);
    }

     void limparDados() {
        NomeFornecedorJTF.setText("");
        CodFornecedorJTF.setText("");
        FoneFornecedorJTF.setText("");
        CnpjFornecedorJTF.setText("");
        BotaoExcluirFornecedor.setEnabled(false);
        BotaoCadastroFornecedor.setEnabled(false);
        BotaoEditarFornecedor.setEnabled(false);
    }
    
    void definirCod() throws DaoException{
        try {
            CodFornecedorJTF.setText(Integer.toString(fControle.proximoCod()));
        } catch (DaoException ex) {
            Logger.getLogger(CUDFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validarFornecedor(Fornecedor a) {
        if (a.getNome().length()>=2 && 
        a.getCnpj().length()>=11 && 
        a.getTelefone().length()>=8){
            return true;
        } else {
            return false;
        }
    }

}
