/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.renatathiago.trabalhoBim2.Ui.JFrames;

import br.cefet.renatathiago.trabalhoBim2.Controle.ClienteControle;
import br.cefet.renatathiago.trabalhoBim2.Entidade.Cliente;
import br.cefet.renatathiago.trabalhoBim2.Entidade.Cliente;
import br.cefet.renatathiago.trabalhoBim2.Excecoes.DaoException;
import br.cefet.renatathiago.trabalhoBim2.Utilidades.CellRenderer;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ClienteJFrame extends javax.swing.JFrame {

  ClienteControle cliControle = new ClienteControle();
  Cliente cli = new Cliente();
  List<Cliente> lista = new ArrayList();
  DefaultTableModel modeloTabela = new DefaultTableModel();
    public ClienteJFrame() {
        initComponents();
        CodClienteJTF.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PadraoFiltroClienteLabel = new javax.swing.JLabel();
        ClienteScrollPanel = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();
        PadraoFiltroClienteJTF = new javax.swing.JTextField();
        FoneClienteLabel = new javax.swing.JLabel();
        BotaoCadastroCliente = new javax.swing.JButton();
        BotaoFiltrarCliente = new javax.swing.JButton();
        BotaoEditarCliente = new javax.swing.JButton();
        FoneClienteJTF = new javax.swing.JTextField();
        FiltroClienteLabel = new javax.swing.JLabel();
        DocClienteLabel = new javax.swing.JLabel();
        BotaoExcluirCliente = new javax.swing.JButton();
        DocClienteJTF = new javax.swing.JTextField();
        FiltroClienteCBox = new javax.swing.JComboBox<>();
        BotaoVoltarMenu = new javax.swing.JButton();
        NomeClienteLabel = new javax.swing.JLabel();
        BotaoSelecionarCliente = new javax.swing.JButton();
        NomeClienteJTF = new javax.swing.JTextField();
        CodClienteLabel = new javax.swing.JLabel();
        CodClienteJTF = new javax.swing.JTextField();
        RuaClienteJTF = new javax.swing.JTextField();
        NumClienteLabel = new javax.swing.JLabel();
        NumClienteJTF = new javax.swing.JTextField();
        BairroClienteLabel = new javax.swing.JLabel();
        BairroClienteJTF = new javax.swing.JTextField();
        CidadeClienteLabel = new javax.swing.JLabel();
        CidadeClienteJTF = new javax.swing.JTextField();
        RuaClienteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PadraoFiltroClienteLabel.setText("Igual a:");

        TabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Telefone", "Cpf"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCliente.setColumnSelectionAllowed(true);
        TabelaCliente.getTableHeader().setReorderingAllowed(false);
        ClienteScrollPanel.setViewportView(TabelaCliente);
        TabelaCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (TabelaCliente.getColumnModel().getColumnCount() > 0) {
            TabelaCliente.getColumnModel().getColumn(0).setResizable(false);
            TabelaCliente.getColumnModel().getColumn(1).setResizable(false);
            TabelaCliente.getColumnModel().getColumn(3).setResizable(false);
        }

        PadraoFiltroClienteJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PadraoFiltroClienteJTFActionPerformed(evt);
            }
        });

        FoneClienteLabel.setText("Telefone");

        BotaoCadastroCliente.setText("Cadastrar");
        BotaoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroClienteActionPerformed(evt);
            }
        });

        BotaoFiltrarCliente.setText("Filtrar");
        BotaoFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFiltrarClienteActionPerformed(evt);
            }
        });

        BotaoEditarCliente.setText("Salvar");
        BotaoEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarClienteActionPerformed(evt);
            }
        });

        FiltroClienteLabel.setText("Filtrar por:");

        DocClienteLabel.setText("Documento");

        BotaoExcluirCliente.setText("Excluir");
        BotaoExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirClienteActionPerformed(evt);
            }
        });

        FiltroClienteCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Nome", "Código" }));
        FiltroClienteCBox.setToolTipText("");
        FiltroClienteCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroClienteCBoxActionPerformed(evt);
            }
        });

        BotaoVoltarMenu.setText("Voltar");
        BotaoVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarMenuActionPerformed(evt);
            }
        });

        NomeClienteLabel.setText("Nome Completo");

        BotaoSelecionarCliente.setText("Selecionar");
        BotaoSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSelecionarClienteActionPerformed(evt);
            }
        });

        NomeClienteJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeClienteJTFActionPerformed(evt);
            }
        });

        CodClienteLabel.setText("Código");

        CodClienteJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodClienteJTFActionPerformed(evt);
            }
        });

        NumClienteLabel.setText("Número");

        BairroClienteLabel.setText("Bairro");

        CidadeClienteLabel.setText("Cidade");

        RuaClienteLabel.setText("Rua");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NomeClienteLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FoneClienteLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodClienteLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeClienteJTF)
                            .addComponent(CodClienteJTF)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FoneClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DocClienteLabel)
                                    .addComponent(DocClienteJTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RuaClienteLabel)
                                .addGap(210, 210, 210))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RuaClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumClienteLabel)
                                    .addComponent(NumClienteJTF)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BairroClienteLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BairroClienteJTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CidadeClienteLabel)
                                    .addComponent(CidadeClienteJTF))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FiltroClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FiltroClienteCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PadraoFiltroClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PadraoFiltroClienteJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoFiltrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotaoSelecionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(BotaoVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClienteScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CodClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NomeClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomeClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FoneClienteLabel)
                            .addComponent(DocClienteLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FoneClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DocClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RuaClienteLabel)
                            .addComponent(NumClienteLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RuaClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BairroClienteLabel)
                            .addComponent(CidadeClienteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BairroClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CidadeClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FiltroClienteCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiltroClienteLabel)
                            .addComponent(PadraoFiltroClienteLabel)
                            .addComponent(PadraoFiltroClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoFiltrarCliente))
                        .addGap(18, 18, 18)
                        .addComponent(ClienteScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastroCliente)
                    .addComponent(BotaoEditarCliente)
                    .addComponent(BotaoExcluirCliente)
                    .addComponent(BotaoVoltarMenu)
                    .addComponent(BotaoSelecionarCliente))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PadraoFiltroClienteJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PadraoFiltroClienteJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PadraoFiltroClienteJTFActionPerformed

    private void BotaoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroClienteActionPerformed

        cli.setDocumento(DocClienteJTF.getText());

        cli.setNome(NomeClienteJTF.getText());
        cli.setTelefone(FoneClienteJTF.getText());
        cli.setTipoCliente("F");
        try {
            if (validarCliente(cli)){
                cliControle.inserirCliente(cli);
                consultarTodos();
                limparDados();
                definirCod();
                habilitarBotaoCadastrar();

            }
        } catch (DaoException ex) {
            Logger.getLogger(ClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoCadastroClienteActionPerformed

    private void BotaoFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFiltrarClienteActionPerformed

        try {
            switch(FiltroClienteCBox.getSelectedIndex()){
                case 0:
                preencherTabela(cliControle.consultarTodos());
                break;
                case 1:
                preencherTabela(cliControle.consultarPorNome(PadraoFiltroClienteJTF.getText()));
                break;
                case 2:
                lista.add(cliControle.consultarPorCod(Integer.parseInt(PadraoFiltroClienteJTF.getText())));
                preencherTabela(lista);
                lista.clear();
                break;
            }
        } catch (DaoException ex) {
            Logger.getLogger(ClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoFiltrarClienteActionPerformed

    private void BotaoEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarClienteActionPerformed
        cli.setCod(Integer.parseInt(CodClienteJTF.getText()));
        cli.setDocumento(DocClienteJTF.getText());
        cli.setNome(NomeClienteJTF.getText());
        cli.setTelefone(FoneClienteJTF.getText());
        try {
            if (validarCliente(cli)){
                cliControle.alterarCliente(Integer.parseInt(CodClienteJTF.getText()), cli);
                consultarTodos();
                limparDados();
                definirCod();
                BotaoEditarCliente.setEnabled(false);
                BotaoCadastroCliente.setEnabled(true);
            }
        } catch (DaoException ex) {
            Logger.getLogger(ClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoEditarClienteActionPerformed

    private void BotaoExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirClienteActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Excluir Cliente", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                cliControle.excluirCliente(Integer.parseInt(CodClienteJTF.getText()));
                limparDados();
                consultarTodos();
                definirCod();
                habilitarBotaoCadastrar();
            } catch (DaoException ex) {
                Logger.getLogger(ClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BotaoExcluirClienteActionPerformed

    private void FiltroClienteCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroClienteCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroClienteCBoxActionPerformed

    private void BotaoVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarMenuActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoVoltarMenuActionPerformed

    private void BotaoSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSelecionarClienteActionPerformed
        try {
            cli = cliControle.consultarPorCod((int) TabelaCliente.getValueAt(TabelaCliente.getSelectedRow(), 0));
            exibirDados(cli);
            habilitarJTF();
            BotaoCadastroCliente.setEnabled(false);
            BotaoEditarCliente.setEnabled(true);

        } catch (DaoException ex) {
            Logger.getLogger(ClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoSelecionarClienteActionPerformed

    private void NomeClienteJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeClienteJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeClienteJTFActionPerformed

    private void CodClienteJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodClienteJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodClienteJTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroClienteJTF;
    private javax.swing.JLabel BairroClienteLabel;
    private javax.swing.JButton BotaoCadastroCliente;
    private javax.swing.JButton BotaoEditarCliente;
    private javax.swing.JButton BotaoExcluirCliente;
    private javax.swing.JButton BotaoFiltrarCliente;
    private javax.swing.JButton BotaoSelecionarCliente;
    private javax.swing.JButton BotaoVoltarMenu;
    private javax.swing.JTextField CidadeClienteJTF;
    private javax.swing.JLabel CidadeClienteLabel;
    private javax.swing.JScrollPane ClienteScrollPanel;
    private javax.swing.JTextField CodClienteJTF;
    private javax.swing.JLabel CodClienteLabel;
    private javax.swing.JTextField DocClienteJTF;
    private javax.swing.JLabel DocClienteLabel;
    private javax.swing.JComboBox<String> FiltroClienteCBox;
    private javax.swing.JLabel FiltroClienteLabel;
    private javax.swing.JTextField FoneClienteJTF;
    private javax.swing.JLabel FoneClienteLabel;
    private javax.swing.JTextField NomeClienteJTF;
    private javax.swing.JLabel NomeClienteLabel;
    private javax.swing.JTextField NumClienteJTF;
    private javax.swing.JLabel NumClienteLabel;
    private javax.swing.JTextField PadraoFiltroClienteJTF;
    private javax.swing.JLabel PadraoFiltroClienteLabel;
    private javax.swing.JTextField RuaClienteJTF;
    private javax.swing.JLabel RuaClienteLabel;
    private javax.swing.JTable TabelaCliente;
    // End of variables declaration//GEN-END:variables
void desabilitarBotaoCadastrar() {
        BotaoCadastroCliente.setEnabled(false);
    }

    void desabilitarBotaoEditar() {
        BotaoEditarCliente.setEnabled(false);
    }

    void desabilitarBotaoExcluir() {
        BotaoExcluirCliente.setEnabled(false);
    }
    void desabilitarBotaoSelecionar() {
        BotaoSelecionarCliente.setEnabled(false);
    }
    
    void habilitarBotaoCadastrar() {
        BotaoCadastroCliente.setEnabled(true);
    }

    void habilitarBotaoEditar() {
        BotaoEditarCliente.setEnabled(true);
    }

    void habilitarBotaoExcluir() {
        BotaoExcluirCliente.setEnabled(true);
    }
    void habilitarBotaoSelecionar() {
        BotaoSelecionarCliente.setEnabled(true);
    }
    void desabilitarJTF(){
        NomeClienteJTF.setEnabled(false);
        FoneClienteJTF.setEnabled(false);
        DocClienteJTF.setEnabled(false);
    }
    void habilitarJTF(){
        NomeClienteJTF.setEnabled(true);
        FoneClienteJTF.setEnabled(true);
        DocClienteJTF.setEnabled(true);
    }

    void preencherTabela(List<Cliente> listaCliente) throws DaoException {
        
        TabelaCliente.setDefaultRenderer(Object.class, new CellRenderer());        
        modeloTabela = (DefaultTableModel) TabelaCliente.getModel();   
        while (modeloTabela.getRowCount() > 0) {
            modeloTabela.removeRow(0);
        }
        for (int i = 0; i<listaCliente.size(); i++) {
            modeloTabela.addRow(new Object[] { 
              listaCliente.get(i).getCod(),
              listaCliente.get(i).getNome(), 
              listaCliente.get(i).getTelefone(), 
              listaCliente.get(i).getDocumento()
            });
        }
    } 

    void consultarTodos() throws DaoException {
        preencherTabela(cliControle.consultarTodos());
    }

     void exibirDados(Cliente a) {
        NomeClienteJTF.setText(a.getNome());
        CodClienteJTF.setText(Integer.toString(a.getCod()));
        FoneClienteJTF.setText(a.getTelefone());
        DocClienteJTF.setText(a.getDocumento());
        BotaoExcluirCliente.setEnabled(true);
    }

     void limparDados() {
        NomeClienteJTF.setText("");
        CodClienteJTF.setText("");
        FoneClienteJTF.setText("");
        DocClienteJTF.setText("");
        BotaoExcluirCliente.setEnabled(false);
        BotaoCadastroCliente.setEnabled(false);
        BotaoEditarCliente.setEnabled(false);
    }
    
    void definirCod() throws DaoException{
        try {
            CodClienteJTF.setText(Integer.toString(cliControle.proximoCod()));
        } catch (DaoException ex) {
            Logger.getLogger(ClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validarCliente(Cliente a) {
        if (a.getNome().length()>=2 && 
        a.getDocumento().length()>=11 && 
        a.getTelefone().length()>=8){
            return true;
        } else {
            return false;
        }
    }
}
