/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.renatathiago.trabalhoBim2.Ui.JFrames;

import br.cefet.renatathiago.trabalhoBim2.Controle.ClienteControle;
import br.cefet.renatathiago.trabalhoBim2.Entidade.Cliente;
import br.cefet.renatathiago.trabalhoBim2.Excecoes.DaoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class CUDCliente extends javax.swing.JFrame {

  ClienteControle cliControle = new ClienteControle();
  Cliente cli = new Cliente();
  List<Cliente> lista = new ArrayList();
  BuscaCliente buscaCliente = new BuscaCliente();
  
    public CUDCliente() {
        initComponents();
        CodClienteJTF.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloCUDProdutos = new javax.swing.JLabel();
        FoneClienteLabel = new javax.swing.JLabel();
        BotaoCadastroCliente = new javax.swing.JButton();
        BotaoEditarCliente = new javax.swing.JButton();
        FoneClienteJTF = new javax.swing.JTextField();
        DocClienteLabel = new javax.swing.JLabel();
        BotaoExcluirCliente = new javax.swing.JButton();
        DocClienteJTF = new javax.swing.JTextField();
        NomeClienteLabel = new javax.swing.JLabel();
        NomeClienteJTF = new javax.swing.JTextField();
        CodClienteLabel = new javax.swing.JLabel();
        CodClienteJTF = new javax.swing.JTextField();
        RuaClienteJTF = new javax.swing.JTextField();
        NumClienteLabel = new javax.swing.JLabel();
        NumClienteJTF = new javax.swing.JTextField();
        BairroClienteLabel = new javax.swing.JLabel();
        BairroClienteJTF = new javax.swing.JTextField();
        CidadeClienteLabel = new javax.swing.JLabel();
        CidadeClienteJTF = new javax.swing.JTextField();
        RuaClienteLabel = new javax.swing.JLabel();
        TituloCUDProdutos1 = new javax.swing.JLabel();
        BotaoBuscarCliente = new javax.swing.JButton();

        TituloCUDProdutos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TituloCUDProdutos.setText("Tela de Produtos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FoneClienteLabel.setText("Telefone");

        BotaoCadastroCliente.setText("Cadastrar");
        BotaoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroClienteActionPerformed(evt);
            }
        });

        BotaoEditarCliente.setText("Salvar");
        BotaoEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarClienteActionPerformed(evt);
            }
        });

        DocClienteLabel.setText("Documento");

        BotaoExcluirCliente.setText("Excluir");
        BotaoExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirClienteActionPerformed(evt);
            }
        });

        NomeClienteLabel.setText("Nome Completo");

        NomeClienteJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeClienteJTFActionPerformed(evt);
            }
        });

        CodClienteLabel.setText("Código");

        CodClienteJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodClienteJTFActionPerformed(evt);
            }
        });

        NumClienteLabel.setText("Número");

        BairroClienteLabel.setText("Bairro");

        CidadeClienteLabel.setText("Cidade");

        RuaClienteLabel.setText("Rua");

        TituloCUDProdutos1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TituloCUDProdutos1.setText("Tela de Cliente");

        BotaoBuscarCliente.setText("Buscar Cliente");
        BotaoBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RuaClienteLabel)
                        .addGap(287, 287, 287))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeClienteLabel)
                            .addComponent(FoneClienteLabel)
                            .addComponent(CodClienteLabel)
                            .addComponent(TituloCUDProdutos1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NomeClienteJTF)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FoneClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DocClienteLabel)
                                    .addComponent(DocClienteJTF)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RuaClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumClienteLabel)
                                    .addComponent(NumClienteJTF)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BairroClienteLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BairroClienteJTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CidadeClienteLabel)
                                    .addComponent(CidadeClienteJTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloCUDProdutos1)
                .addGap(18, 18, 18)
                .addComponent(CodClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NomeClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomeClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FoneClienteLabel)
                    .addComponent(DocClienteLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FoneClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DocClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RuaClienteLabel)
                    .addComponent(NumClienteLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RuaClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BairroClienteLabel)
                    .addComponent(CidadeClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BairroClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CidadeClienteJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastroCliente)
                    .addComponent(BotaoEditarCliente)
                    .addComponent(BotaoExcluirCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroClienteActionPerformed

        cli.setDocumento(DocClienteJTF.getText());

        cli.setNome(NomeClienteJTF.getText());
        cli.setTelefone(FoneClienteJTF.getText());
        cli.setTipoCliente("F");
        try {
            if (validarCliente(cli)){
                cliControle.inserirCliente(cli);
                limparDados();
                definirCod();
                habilitarBotaoCadastrar();

            }
        } catch (DaoException ex) {
            Logger.getLogger(CUDCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoCadastroClienteActionPerformed

    private void BotaoEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarClienteActionPerformed
        cli.setCod(Integer.parseInt(CodClienteJTF.getText()));
        cli.setDocumento(DocClienteJTF.getText());
        cli.setNome(NomeClienteJTF.getText());
        cli.setTelefone(FoneClienteJTF.getText());
        try {
            if (validarCliente(cli)){
                cliControle.alterarCliente(Integer.parseInt(CodClienteJTF.getText()), cli);
                limparDados();
                definirCod();
                BotaoEditarCliente.setEnabled(false);
                BotaoCadastroCliente.setEnabled(true);
            }
        } catch (DaoException ex) {
            Logger.getLogger(CUDCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoEditarClienteActionPerformed

    private void BotaoExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirClienteActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Excluir Cliente", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                cliControle.excluirCliente(Integer.parseInt(CodClienteJTF.getText()));
                limparDados();
                definirCod();
                habilitarBotaoCadastrar();
            } catch (DaoException ex) {
                Logger.getLogger(CUDCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BotaoExcluirClienteActionPerformed

    private void NomeClienteJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeClienteJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeClienteJTFActionPerformed

    private void CodClienteJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodClienteJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodClienteJTFActionPerformed

    private void BotaoBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarClienteActionPerformed
        buscaCliente.setVisible(true);
        dispose();
        try {
            buscaCliente.consultarTodos();
        } catch (DaoException ex) {
            Logger.getLogger(CUDProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotaoBuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroClienteJTF;
    private javax.swing.JLabel BairroClienteLabel;
    private javax.swing.JButton BotaoBuscarCliente;
    private javax.swing.JButton BotaoCadastroCliente;
    private javax.swing.JButton BotaoEditarCliente;
    private javax.swing.JButton BotaoExcluirCliente;
    private javax.swing.JTextField CidadeClienteJTF;
    private javax.swing.JLabel CidadeClienteLabel;
    private javax.swing.JTextField CodClienteJTF;
    private javax.swing.JLabel CodClienteLabel;
    private javax.swing.JTextField DocClienteJTF;
    private javax.swing.JLabel DocClienteLabel;
    private javax.swing.JTextField FoneClienteJTF;
    private javax.swing.JLabel FoneClienteLabel;
    private javax.swing.JTextField NomeClienteJTF;
    private javax.swing.JLabel NomeClienteLabel;
    private javax.swing.JTextField NumClienteJTF;
    private javax.swing.JLabel NumClienteLabel;
    private javax.swing.JTextField RuaClienteJTF;
    private javax.swing.JLabel RuaClienteLabel;
    private javax.swing.JLabel TituloCUDProdutos;
    private javax.swing.JLabel TituloCUDProdutos1;
    // End of variables declaration//GEN-END:variables
void desabilitarBotaoCadastrar() {
        BotaoCadastroCliente.setEnabled(false);
    }

    void desabilitarBotaoEditar() {
        BotaoEditarCliente.setEnabled(false);
    }

    void desabilitarBotaoExcluir() {
        BotaoExcluirCliente.setEnabled(false);
    }
    
    void habilitarBotaoCadastrar() {
        BotaoCadastroCliente.setEnabled(true);
    }

    void habilitarBotaoEditar() {
        BotaoEditarCliente.setEnabled(true);
    }

    void habilitarBotaoExcluir() {
        BotaoExcluirCliente.setEnabled(true);
    }

    void desabilitarJTF(){
        NomeClienteJTF.setEnabled(false);
        FoneClienteJTF.setEnabled(false);
        DocClienteJTF.setEnabled(false);
    }
    void habilitarJTF(){
        NomeClienteJTF.setEnabled(true);
        FoneClienteJTF.setEnabled(true);
        DocClienteJTF.setEnabled(true);
    }

     void exibirDados(Cliente a) {
        NomeClienteJTF.setText(a.getNome());
        CodClienteJTF.setText(Integer.toString(a.getCod()));
        FoneClienteJTF.setText(a.getTelefone());
        DocClienteJTF.setText(a.getDocumento());
        BotaoExcluirCliente.setEnabled(true);
    }

     void limparDados() {
        NomeClienteJTF.setText("");
        CodClienteJTF.setText("");
        FoneClienteJTF.setText("");
        DocClienteJTF.setText("");
        BotaoExcluirCliente.setEnabled(false);
        BotaoCadastroCliente.setEnabled(false);
        BotaoEditarCliente.setEnabled(false);
    }
    
    void definirCod() throws DaoException{
        try {
            CodClienteJTF.setText(Integer.toString(cliControle.proximoCod()));
        } catch (DaoException ex) {
            Logger.getLogger(CUDCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validarCliente(Cliente a) {
        if (a.getNome().length()>=2 && 
        a.getDocumento().length()>=11 && 
        a.getTelefone().length()>=8){
            return true;
        } else {
            return false;
        }
    }
}
