/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Raissa_Tassis.TrabalhoBim1.Ui.Telas;

import br.com.Raissa_Tassis.TrabalhoBim1.Controle.HqControle;
import br.com.Raissa_Tassis.TrabalhoBim1.Dao.DaoException;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Hq;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Obra;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Usuario;
import br.com.Raissa_Tassis.TrabalhoBim1.Ui.HqRelatorio;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.lang.Double.parseDouble;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author José Fernandes
 */
public class HqRelatorioJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HqListaJFrame
     */
    private HqControle hqControle = HqControle.getInstance();
    private Usuario uLogado;
    private List<Hq> hqs;

    public HqRelatorioJFrame(Usuario uLogado) {
        initComponents();
        this.uLogado = uLogado;
//        List<Hq> hqList = null;
//        try {
//            hqList = hqControle.consultaTudoUsuario(uLogado);
//        } catch (DaoException ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
//        }
//
        preencheTabela(null);
        this.setLocationRelativeTo(null);
        this.setTitle("Relatório HQs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        tfPreco2 = new javax.swing.JTextField();
        tfPreco1 = new javax.swing.JTextField();
        lblPreco1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btPesquisa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btEmitir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHq = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblNome.setText("    Nome:");

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyPressed(evt);
            }
        });

        lblPreco.setText("Preço:");

        tfPreco2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPreco2KeyPressed(evt);
            }
        });

        tfPreco1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPreco1KeyPressed(evt);
            }
        });

        lblPreco1.setText("   -");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPreco)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        btPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/zoom.png"))); // NOI18N
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btPesquisa)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        btEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/report.png"))); // NOI18N
        btEmitir.setText("Emitir Relatório");
        btEmitir.setEnabled(false);
        btEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmitirActionPerformed(evt);
            }
        });
        jPanel2.add(btEmitir);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        tbHq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHq);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyPressed
 
    }//GEN-LAST:event_tfPesquisaKeyPressed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed

        try{
            String nome = tfPesquisa.getText();
            Double preco1 = parseDouble(tfPreco1.getText());
            Double preco2 = parseDouble(tfPreco2.getText());
            
            if(preco1 >= 0 && preco2 >= 0){
                
                hqs = hqControle.consultaRelatorio(nome, preco1, preco2);
                preencheTabela(hqs);        
                btEmitir.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(this, "Preço negativo não vale" ,"Preço inválido!", HEIGHT);
            }

        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Preço inválido!", HEIGHT);
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro na consulta!", HEIGHT);
        }
        
        
                
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void tbHqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHqMouseClicked
    }//GEN-LAST:event_tbHqMouseClicked

    private void btEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmitirActionPerformed
        if(hqs != null){
            HqRelatorio hqRel = new HqRelatorio();
            hqRel.emitirRelatorio(hqs);
        }
    }//GEN-LAST:event_btEmitirActionPerformed

    private void tfPreco2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPreco2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPreco2KeyPressed

    private void tfPreco1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPreco1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPreco1KeyPressed

    public Hq getHqFromTable() {
        Hq hqRet = null;

        int linha = tbHq.getSelectedRow();

        if (linha >= 0) {
            TableModel m = tbHq.getModel();
            String idStr = m.getValueAt(linha, 0).toString();
            int id = Integer.parseInt(idStr);

            hqRet = new Hq();
            hqRet.setCdHq(id);
            hqRet.setNmHq(m.getValueAt(linha, 1).toString());
            hqRet.setPreco(parseDouble(m.getValueAt(linha, 2).toString()));
            hqRet.setConservacao(m.getValueAt(linha, 3).toString());
        }
        return hqRet;
    }

    public void preencheTabela(List<Hq> hqList) {
        if (hqList != null) {
            String[] strVet = new String[]{"Cod.", "Nome", "Preço", "Conservação"};
            String[][] strAMat = new String[hqList.size()][4];

            for (int i = 0; i < hqList.size(); i++) {
                Hq hq = hqList.get(i);
                strAMat[i][0] = hq.getCdHq() + "";
                strAMat[i][1] = hq.getNmHq();
                strAMat[i][2] = hq.getPreco() + "";
                strAMat[i][3] = hq.getConservacao();
            }

            tbHq.setModel(new DefaultTableModel(
                    strAMat, strVet));
        }

        desabilitarBotoes();
    }

    private void desabilitarBotoes() {
        btEmitir.setEnabled(false);
    }

    private void consultaPorNome() {
        List<Hq> hqList = null;
        
        try {
            hqList = hqControle.consultaPorNomeUsuario(tfPesquisa.getText(), uLogado);
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
       
        preencheTabela(hqList);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HqRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HqRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HqRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HqRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HqRelatorioJFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEmitir;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JTable tbHq;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfPreco1;
    private javax.swing.JTextField tfPreco2;
    // End of variables declaration//GEN-END:variables
}
