/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Raissa_Tassis.TrabalhoBim1.Ui.Telas;

import br.com.Raissa_Tassis.TrabalhoBim1.Controle.CompraControle;
import br.com.Raissa_Tassis.TrabalhoBim1.Controle.UsuarioControle;
import br.com.Raissa_Tassis.TrabalhoBim1.Dao.DaoException;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Compra;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Editora;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Usuario;
import br.com.Raissa_Tassis.TrabalhoBim1.Utils.DateParse;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Usuario uLogado;
    CompraControle cControle = CompraControle.getInstance();
    UsuarioControle uControle = UsuarioControle.getInstance();

    public MainJFrame(Usuario logado) {
        uLogado = logado;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Principal");

        try {
            List<Compra> cList = cControle.consultaPorComprador(uLogado.getCdUsuario());
            preencheTabela(cList);
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        btHqLista = new javax.swing.JButton();
        btListaDesejo = new javax.swing.JButton();
        btUsuarioPerfil = new javax.swing.JButton();
        PanelTable = new javax.swing.JScrollPane();
        tbCompra = new javax.swing.JTable();
        PanelHeader = new javax.swing.JPanel();
        PanelLogo = new javax.swing.JPanel();
        lblBemVindo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        btVerCompras = new javax.swing.JButton();
        JMenu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCategoria = new javax.swing.JMenuItem();
        MenuEditora = new javax.swing.JMenuItem();
        MenuObras = new javax.swing.JMenuItem();
        MenuHqs = new javax.swing.JMenuItem();
        MenuCompra = new javax.swing.JMenu();
        ItemComprarHq = new javax.swing.JMenuItem();
        ItemMinhasCompras = new javax.swing.JMenuItem();
        MenuVenda = new javax.swing.JMenu();
        ItemMinhasVendas = new javax.swing.JMenuItem();
        MenuUsuario = new javax.swing.JMenu();
        ListarUsuarios = new javax.swing.JMenuItem();
        PerfilUsuario = new javax.swing.JMenuItem();
        MenuItemEndereco = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        ObraRelatorio = new javax.swing.JMenuItem();
        HqRelatorio = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        ItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        PanelMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btHqLista.setBackground(new java.awt.Color(102, 0, 0));
        btHqLista.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btHqLista.setForeground(new java.awt.Color(255, 255, 255));
        btHqLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/book_go.png"))); // NOI18N
        btHqLista.setText("Minhas HQs");
        btHqLista.setFocusable(false);
        btHqLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHqListaActionPerformed(evt);
            }
        });

        btListaDesejo.setBackground(new java.awt.Color(102, 0, 0));
        btListaDesejo.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btListaDesejo.setForeground(new java.awt.Color(255, 255, 255));
        btListaDesejo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/book_key.png"))); // NOI18N
        btListaDesejo.setText("Lista de Desejo");
        btListaDesejo.setFocusable(false);

        btUsuarioPerfil.setBackground(new java.awt.Color(102, 0, 0));
        btUsuarioPerfil.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btUsuarioPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btUsuarioPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/user_suit.png"))); // NOI18N
        btUsuarioPerfil.setText("Meu perfil");
        btUsuarioPerfil.setFocusable(false);
        btUsuarioPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btUsuarioPerfil)
                            .addComponent(btHqLista))
                        .addGap(9, 9, 9))
                    .addComponent(btListaDesejo))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btHqLista)
                .addGap(39, 39, 39)
                .addComponent(btListaDesejo)
                .addGap(39, 39, 39)
                .addComponent(btUsuarioPerfil)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tbCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCompra.setEnabled(false);
        PanelTable.setViewportView(tbCompra);

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblBemVindo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(102, 0, 0));
        lblBemVindo.setText("Bem-vindo à Comic Universe!!");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(51, 0, 0));
        lblDescricao.setText("A sua loja de HQs");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/logoTransparente.png"))); // NOI18N

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBemVindo)
                    .addGroup(PanelLogoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblHeader.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        lblHeader.setText("Minhas últimas compras");

        btVerCompras.setBackground(new java.awt.Color(102, 0, 0));
        btVerCompras.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        btVerCompras.setForeground(new java.awt.Color(255, 255, 255));
        btVerCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/cart_go.png"))); // NOI18N
        btVerCompras.setText("Ver mais");
        btVerCompras.setFocusable(false);

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/add.png"))); // NOI18N
        MenuCadastro.setText("Cadastro");
        MenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroActionPerformed(evt);
            }
        });

        MenuCategoria.setText("Categoria");
        MenuCategoria.setActionCommand("Categorias");
        MenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCategoria);

        MenuEditora.setText("Editora");
        MenuEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditoraActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuEditora);

        MenuObras.setText("Obras");
        MenuObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuObrasActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuObras);

        MenuHqs.setText("HQs");
        MenuHqs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHqsActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuHqs);

        JMenu.add(MenuCadastro);

        MenuCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/cart.png"))); // NOI18N
        MenuCompra.setText("Comprar");

        ItemComprarHq.setText("Comprar HQs");
        MenuCompra.add(ItemComprarHq);

        ItemMinhasCompras.setText("Minhas compras");
        MenuCompra.add(ItemMinhasCompras);

        JMenu.add(MenuCompra);

        MenuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/money.png"))); // NOI18N
        MenuVenda.setText("Vendas");

        ItemMinhasVendas.setText("Minhas vendas");
        MenuVenda.add(ItemMinhasVendas);

        JMenu.add(MenuVenda);

        MenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/user_go.png"))); // NOI18N
        MenuUsuario.setText("Usuários");
        MenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuarioActionPerformed(evt);
            }
        });

        ListarUsuarios.setText("Listar todos usuários");
        ListarUsuarios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ListarUsuariosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuariosActionPerformed(evt);
            }
        });
        MenuUsuario.add(ListarUsuarios);

        PerfilUsuario.setText("Meu Perfil");
        PerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(PerfilUsuario);

        MenuItemEndereco.setText("Endereços");
        MenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEnderecoActionPerformed(evt);
            }
        });
        MenuUsuario.add(MenuItemEndereco);

        JMenu.add(MenuUsuario);

        MenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/report.png"))); // NOI18N
        MenuRelatorio.setText("Relatórios");

        ObraRelatorio.setText("Obra");
        ObraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObraRelatorioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(ObraRelatorio);

        HqRelatorio.setText("HQ");
        HqRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HqRelatorioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(HqRelatorio);

        JMenu.add(MenuRelatorio);

        MenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/information.png"))); // NOI18N
        MenuSobre.setText("Sobre");

        ItemSobre.setText("Sobre nós");
        MenuSobre.add(ItemSobre);

        JMenu.add(MenuSobre);

        setJMenuBar(JMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btVerCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btVerCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHeader))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaActionPerformed
        CategoriaListaJFrame aL = new CategoriaListaJFrame();
        aL.setVisible(true);
    }//GEN-LAST:event_MenuCategoriaActionPerformed

    private void MenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadastroActionPerformed

    private void MenuObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuObrasActionPerformed
        ObraListaJFrame oL = new ObraListaJFrame();
        oL.setVisible(true);
    }//GEN-LAST:event_MenuObrasActionPerformed

    private void MenuHqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHqsActionPerformed
        HqListaJFrame hqL = new HqListaJFrame(uLogado);
        hqL.setVisible(true);
        try {
            uLogado = uControle.consultaPorCd(uLogado.getCdUsuario());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
    }//GEN-LAST:event_MenuHqsActionPerformed

    private void MenuEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditoraActionPerformed
        EditoraListaJFrame eL = new EditoraListaJFrame();
        eL.setVisible(true);
    }//GEN-LAST:event_MenuEditoraActionPerformed

    private void btHqListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHqListaActionPerformed
        HqListaJFrame hqL = new HqListaJFrame(uLogado);
        hqL.setVisible(true);
        try {
            uLogado = uControle.consultaPorCd(uLogado.getCdUsuario());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
    }//GEN-LAST:event_btHqListaActionPerformed

    private void ListarUsuariosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ListarUsuariosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarUsuariosAncestorAdded

    private void ListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuariosActionPerformed
        UsuarioListaJDialog uLista = new UsuarioListaJDialog(this, true);
        uLista.setVisible(true);
    }//GEN-LAST:event_ListarUsuariosActionPerformed

    private void MenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuarioActionPerformed
        UsuarioPerfilJFrame uPerfil = new UsuarioPerfilJFrame(this.uLogado);
        uPerfil.setVisible(true);
        try {
            uLogado = uControle.consultaPorCd(uLogado.getCdUsuario());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
    }//GEN-LAST:event_MenuUsuarioActionPerformed

    private void btUsuarioPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioPerfilActionPerformed
        UsuarioPerfilJFrame uPerfil = new UsuarioPerfilJFrame(this.uLogado);
        uPerfil.setVisible(true);
        try {
            uLogado = uControle.consultaPorCd(uLogado.getCdUsuario());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
    }//GEN-LAST:event_btUsuarioPerfilActionPerformed

    private void MenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEnderecoActionPerformed
        EnderecoListaJFrame eLista = new EnderecoListaJFrame(uLogado);
        eLista.setVisible(true);
        try {
            uLogado = uControle.consultaPorCd(uLogado.getCdUsuario());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
    }//GEN-LAST:event_MenuItemEnderecoActionPerformed

    private void PerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilUsuarioActionPerformed
        UsuarioPerfilJFrame uPerfil = new UsuarioPerfilJFrame(this.uLogado);
        uPerfil.setVisible(true);
        try {
            uLogado = uControle.consultaPorCd(uLogado.getCdUsuario());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
    }//GEN-LAST:event_PerfilUsuarioActionPerformed

    private void HqRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HqRelatorioActionPerformed
        HqRelatorioJFrame hqRel = new HqRelatorioJFrame(uLogado);
        hqRel.setVisible(true);
    }//GEN-LAST:event_HqRelatorioActionPerformed

    private void ObraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObraRelatorioActionPerformed
        ObraRelatorioJFrame oRel = new ObraRelatorioJFrame(uLogado);
        oRel.setVisible(true);
    }//GEN-LAST:event_ObraRelatorioActionPerformed

    public void preencheTabela(List<Compra> cList) {
        if (cList != null) {
            String[] strVet = new String[]{"Cod.", "Data", "Valor", "Comprador", "Vendedor"};
            String[][] strAMat = new String[cList.size()][5];

            for (int i = 0; i < cList.size(); i++) {
                Compra c = cList.get(i);
                strAMat[i][0] = c.getCdCompra() + "";
                strAMat[i][1] = DateParse.dateToString(c.getDtCompra());
                strAMat[i][2] = c.getValorCompra() + "";
                strAMat[i][3] = c.getComprador().getNmUsuario();
                strAMat[i][4] = c.getVendedor().getNmUsuario();
            }

            tbCompra.setModel(new DefaultTableModel(
                    strAMat, strVet));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HqRelatorio;
    private javax.swing.JMenuItem ItemComprarHq;
    private javax.swing.JMenuItem ItemMinhasCompras;
    private javax.swing.JMenuItem ItemMinhasVendas;
    private javax.swing.JMenuItem ItemSobre;
    private javax.swing.JMenuBar JMenu;
    private javax.swing.JMenuItem ListarUsuarios;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuCategoria;
    private javax.swing.JMenu MenuCompra;
    private javax.swing.JMenuItem MenuEditora;
    private javax.swing.JMenuItem MenuHqs;
    private javax.swing.JMenuItem MenuItemEndereco;
    private javax.swing.JMenuItem MenuObras;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JMenu MenuVenda;
    private javax.swing.JMenuItem ObraRelatorio;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JScrollPane PanelTable;
    private javax.swing.JMenuItem PerfilUsuario;
    private javax.swing.JButton btHqLista;
    private javax.swing.JButton btListaDesejo;
    private javax.swing.JButton btUsuarioPerfil;
    private javax.swing.JButton btVerCompras;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tbCompra;
    // End of variables declaration//GEN-END:variables
}
