/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Raissa_Tassis.TrabalhoBim1.Ui.Telas;

import br.com.Raissa_Tassis.TrabalhoBim1.Controle.HqControle;
import br.com.Raissa_Tassis.TrabalhoBim1.Controle.ObraControle;
import br.com.Raissa_Tassis.TrabalhoBim1.Dao.DaoException;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Hq;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Obra;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Usuario;
import br.com.Raissa_Tassis.TrabalhoBim1.Ui.HqRelatorio;
import br.com.Raissa_Tassis.TrabalhoBim1.Ui.ObraRelatorio;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.lang.Double.parseDouble;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author José Fernandes
 */
public class ObraRelatorioJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HqListaJFrame
     */
    private ObraControle oControle = ObraControle.getInstance();
    private Usuario uLogado;
    private List<Obra> obras;

    public ObraRelatorioJFrame(Usuario uLogado) {
        initComponents();
        this.uLogado = uLogado;
//        List<Hq> hqList = null;
//        try {
//            hqList = hqControle.consultaTudoUsuario(uLogado);
//        } catch (DaoException ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
//        }
//
        preencheTabela(null);
        this.setLocationRelativeTo(null);
        this.setTitle("Relatório Obras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lblLancamento = new javax.swing.JLabel();
        tfLancamento2 = new javax.swing.JTextField();
        tfLancamento1 = new javax.swing.JTextField();
        lblPreco1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btPesquisa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btEmitir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbObra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblNome.setText("    Nome:");

        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
        });

        lblLancamento.setText("Lançamento:");

        tfLancamento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLancamento2KeyPressed(evt);
            }
        });

        tfLancamento1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLancamento1KeyPressed(evt);
            }
        });

        lblPreco1.setText("   -");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLancamento)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfLancamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLancamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLancamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLancamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        btPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/zoom.png"))); // NOI18N
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btPesquisa)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        btEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/report.png"))); // NOI18N
        btEmitir.setText("Emitir Relatório");
        btEmitir.setEnabled(false);
        btEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmitirActionPerformed(evt);
            }
        });
        jPanel2.add(btEmitir);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        tbObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbObraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbObra);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
 
    }//GEN-LAST:event_tfNomeKeyPressed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed

        try{
            String nome = tfNome.getText();
            int ano1 = Integer.parseInt(tfLancamento1.getText());
            int ano2 = Integer.parseInt(tfLancamento2.getText());
            
            if(ano1 >= 0 && ano2 >= 0){
                
                obras = oControle.consultaRelatorio(nome, ano1, ano2);
                preencheTabela(obras);        
                btEmitir.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(this, "Preço negativo não vale" ,"Preço inválido!", HEIGHT);
            }
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Preço inválido!", HEIGHT);
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro na consulta!", HEIGHT);
        }
        
        
                
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void tbObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbObraMouseClicked
    }//GEN-LAST:event_tbObraMouseClicked

    private void btEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmitirActionPerformed
        if(obras != null){
            ObraRelatorio oRel = new ObraRelatorio();
            oRel.emitirRelatorio(obras);
        }
    }//GEN-LAST:event_btEmitirActionPerformed

    private void tfLancamento2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLancamento2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLancamento2KeyPressed

    private void tfLancamento1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLancamento1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLancamento1KeyPressed

    public Hq getHqFromTable() {
        Hq hqRet = null;

        int linha = tbObra.getSelectedRow();

        if (linha >= 0) {
            TableModel m = tbObra.getModel();
            String idStr = m.getValueAt(linha, 0).toString();
            int id = Integer.parseInt(idStr);

            hqRet = new Hq();
            hqRet.setCdHq(id);
            hqRet.setNmHq(m.getValueAt(linha, 1).toString());
            hqRet.setPreco(parseDouble(m.getValueAt(linha, 2).toString()));
            hqRet.setConservacao(m.getValueAt(linha, 3).toString());
        }
        return hqRet;
    }

    public void preencheTabela(List<Obra> oList) {
        if (oList != null) {
            String[] strVet = new String[]{"Cod.", "Nome", "Lançamento"};
            String[][] strAMat = new String[oList.size()][3];

            for (int i = 0; i < oList.size(); i++) {
                Obra o = oList.get(i);
                strAMat[i][0] = o.getCdObra()+ "";
                strAMat[i][1] = o.getNmObra();
                strAMat[i][2] = o.getDtLancamento() + "";
            }

            tbObra.setModel(new DefaultTableModel(
                    strAMat, strVet));
        }

        desabilitarBotoes();
    }

    private void desabilitarBotoes() {
        btEmitir.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObraRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObraRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObraRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObraRelatorioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObraRelatorioJFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEmitir;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLancamento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JTable tbObra;
    private javax.swing.JTextField tfLancamento1;
    private javax.swing.JTextField tfLancamento2;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
