/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Raissa_Tassis.TrabalhoBim1.Ui.Telas;

import br.com.Raissa_Tassis.TrabalhoBim1.Controle.ObraControle;
import br.com.Raissa_Tassis.TrabalhoBim1.Dao.DaoException;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Categoria;
import br.com.Raissa_Tassis.TrabalhoBim1.Entidade.Obra;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author José Fernandes
 */
public class ObraListaJFrame extends javax.swing.JFrame {

    ObraControle oControle = ObraControle.getInstance();

    /**
     *
     * Creates new form ObraListaJFrame
     */
    public ObraListaJFrame() {
        initComponents();
        List<Obra> oList = null;
        try {
            oList = oControle.consultaTudo();
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }

        preencheTabela(oList);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Obra");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panelHead = new javax.swing.JPanel();
        panelAdd = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        panelPesquisa = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObraTable = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelHead.setLayout(new java.awt.BorderLayout());

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/add.png"))); // NOI18N
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        panelAdd.add(btAdd);

        panelHead.add(panelAdd, java.awt.BorderLayout.EAST);

        panelPesquisa.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblNome.setText("Nome:");
        panelPesquisa.add(lblNome);

        tfPesquisa.setColumns(30);
        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyPressed(evt);
            }
        });
        panelPesquisa.add(tfPesquisa);

        panelHead.add(panelPesquisa, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelHead, java.awt.BorderLayout.NORTH);

        ObraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ObraTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObraTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ObraTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        panelButton.add(btExcluir);

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/pencil.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        panelButton.add(btAlterar);

        btVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Raissa_Tassis/TrabalhoBim1/Ui/Imagens/cursor.png"))); // NOI18N
        btVisualizar.setText("Visualizar");
        btVisualizar.setEnabled(false);
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });
        panelButton.add(btVisualizar);

        getContentPane().add(panelButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        ObraCadastroJDialog telaCad = new ObraCadastroJDialog(this, true);
        telaCad.setVisible(true);
        
        Obra o = telaCad.getObra();
        
        if (o != null) {
            tfPesquisa.setText(o.getNmObra());
            consultaPorNome();
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void ObraTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObraTableMouseClicked
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        btVisualizar.setEnabled(true);
    }//GEN-LAST:event_ObraTableMouseClicked

    private void tfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyPressed
        if (evt.getKeyCode() == 10) {
            consultaPorNome();
        }
    }//GEN-LAST:event_tfPesquisaKeyPressed

    private void consultaPorNome() {
        List<Obra> oList = null;
        try {
            oList = oControle.consultaPorNome(tfPesquisa.getText());
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
        preencheTabela(oList);
    }

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir", "Exclusão", WIDTH);
        List<Obra> oList = null;

        if (opt == JOptionPane.OK_OPTION) {
            Obra obra = getObraFromTable();
            try {
                oControle.excluir(obra.getCdObra());

                int linha = ObraTable.getSelectedRow();
                DefaultTableModel m = (DefaultTableModel) ObraTable.getModel();
                m.removeRow(linha);
                desabilitarBotoes();

            } catch (DaoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        List<Obra> oList = null;

        Obra o = getObraFromTable();
        ObraAlterarJDialog tela = new ObraAlterarJDialog(this, true, o);
        tela.setVisible(true);

        try {
            oList = oControle.consultaTudo();
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro no BD ", HEIGHT);
        }
        preencheTabela(oList);
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        Obra obra = getObraFromTable();
        ObraVisualizarJDialog telaVer = new ObraVisualizarJDialog(this, true, obra);
        telaVer.setVisible(true);
    }//GEN-LAST:event_btVisualizarActionPerformed

    public Obra getObraFromTable() {
        Obra obraRet = null;

        int linha = ObraTable.getSelectedRow();

        if (linha >= 0) {
            TableModel m = ObraTable.getModel();
            String idStr = m.getValueAt(linha, 0).toString();
            int id = Integer.parseInt(idStr);

            obraRet = new Obra();
            obraRet.setCdObra(id);
            obraRet.setNmObra(m.getValueAt(linha, 1).toString());
            obraRet.setDtLancamento(Integer.parseInt(m.getValueAt(linha, 2).toString()));
        }
        return obraRet;
    }

    public void preencheTabela(List<Obra> oList) {
        if (oList != null) {
            String[] strVet = new String[]{"Cod.", "Nome", "Lancamento"};
            String[][] strAMat = new String[oList.size()][3];

            for (int i = 0; i < oList.size(); i++) {
                Obra o = oList.get(i);
                strAMat[i][0] = o.getCdObra() + "";
                strAMat[i][1] = o.getNmObra();
                strAMat[i][2] = o.getDtLancamento()+"";
            }

            ObraTable.setModel(new DefaultTableModel(
                    strAMat, strVet));
        }

        desabilitarBotoes();
    }

    private void desabilitarBotoes() {
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        btVisualizar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObraListaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObraListaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObraListaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObraListaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObraListaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ObraTable;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelPesquisa;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
